[window]
title = "Final Project"
initial_width = 1280
initial_height = 720

[camera]
fov = 80 # this is in degrees
[camera.freecam]
initial_position = [5.0, 0.0, 0.0]
initial_forward = [-1.0, 0.0, 0.0]
move_speed = 0.2
look_speed = 0.005                 # this is basically sensitivity
# [camera.battlecruiser]

# [camera.minimap]

[planets]
ico_mesh_resolution = 5
# TODO: add star params
# TODO: add earth params
# TODO: add default solar system parameters like so:
planets_info = [
# example entries:
# [type, radius, parent_id = -1] -> no orbit, static planet at (0, 0, 0) OR
# [type, radius, parent_id, orbit_direction, orbit_small_r, orbit_large_r, orbit_normal, orbit_period]
# type can be "star", "earth", or "body" for now

    # Default single planet system
#   ["star", 4.0, -1, [0.0, 0.0, 0.0], 0.0, 0.0, [0.0, 1.0, 0.0], 0.0],
#   ["earth", 1.0, 0, [1.0, 0.0, 0.0], 40.0, 40.0, [0.0, 1.0, 0.0], 1000000.0],
#   ["body", 1.5, 1, [0.0, 0.0, 1.0], 6.0, 6.0, [0.0, 1.0, 0.0], 2.0],

    # Example multi-planet system
    # Star
    ["star", 6.0, -1, [0.0, 0.0, 0.0], 0.0, 0.0, [0.0, 1.0, 0.0], 0.0],

    # Planets
    ["earth", 2.0, 0, [12.0, 0.0, 0.0], 20.0, 22.0, [0.0, 1.0, 0.0], 12.0],
    ["earth", 1.8, 0, [18.0, 0.0, 0.0], 26.0, 28.0, [0.0, 1.0, 0.0], 20.0],
    ["earth", 2.5, 0, [24.0, 0.0, 0.0], 32.0, 34.0, [0.0, 1.0, 0.0], 32.0],
    ["earth", 1.6, 0, [30.0, 0.0, 0.0], 38.0, 40.0, [0.0, 1.0, 0.0], 48.0],
    ["earth", 3.0, 0, [36.0, 0.0, 0.0], 44.0, 46.0, [0.0, 1.0, 0.0], 70.0],
    ["earth", 2.2, 0, [42.0, 0.0, 0.0], 50.0, 52.0, [0.0, 1.0, 0.0], 90.0],

    # Moons / small bodies
    ["body", 0.4, 1, [1.0, 0.0, 0.0], 3.0, 4.0, [0.0, 1.0, 0.0], 2.0],
    ["body", 0.3, 1, [0.0, 0.0, 1.0], 4.5, 5.5, [0.0, 1.0, 0.0], 3.0],
    ["body", 0.35, 2, [1.0, 1.0, 0.0], 3.0, 4.0, [0.0, 0.0, 1.0], 2.5],
    ["body", 0.25, 2, [0.0, 1.0, 1.0], 4.0, 5.0, [1.0, 0.0, 0.0], 3.5],
    ["body", 0.5, 3, [1.0, 0.0, 1.0], 5.0, 6.0, [0.0, 1.0, 1.0], 4.0],
    ["body", 0.35, 3, [0.0, 1.0, 0.0], 6.0, 7.0, [1.0, 0.0, 0.0], 5.0],
    ["body", 0.4, 4, [0.0, 0.0, 1.0], 2.5, 3.5, [0.0, 1.0, 0.0], 1.5],
    ["body", 0.3, 4, [1.0, 1.0, 0.0], 3.5, 4.5, [0.0, 0.0, 1.0], 2.5],
    ["body", 0.45, 5, [1.0, 0.0, 0.0], 5.5, 6.5, [0.0, 1.0, 1.0], 4.5],
    ["body", 0.35, 5, [0.0, 1.0, 1.0], 6.5, 7.5, [1.0, 0.0, 1.0], 5.5],
    ["body", 0.4, 6, [0.0, 1.0, 0.0], 4.0, 5.0, [1.0, 0.0, 0.0], 3.0],
    ["body", 0.3, 6, [1.0, 0.0, 1.0], 5.0, 6.0, [0.0, 1.0, 1.0], 4.0],
]

[skybox]
# TODO: skybox paths could go here

[battlecruiser]
# TODO: battlecruiser model path could go here
[battlecruiser.thrusters]
# TODO: battlecruiser thruster particle params could go here
